version: '2.7'

rpc:
    listen: tcp://127.0.0.1:6001

server:
    command: "php app.php"
    relay: pipes
    on_init:
        command: "php app.php configure"

static:
    dir: "public"

http:
    address: 0.0.0.0:8080
    middleware: [ "gzip", "static" ]
    static:
        dir: "public"
        forbid: [ ".php", ".htaccess" ]
    pool:
        num_workers: 1
        debug: true

jobs:
    consume: [ default ]
    pipelines:
        default:
            driver: memory
            config: {}
    pool:
        num_workers: 16

kv:
    local:
        driver: memory
        config:
            interval: 60

metrics:
    address: localhost:2112

temporal:
    address: 127.0.0.1:7233
    namespace: default
    activities:
        num_workers: 4

logs:
    level: info
    channels:
        server:
            level: info

#grpc:
#    listen: "tcp://0.0.0.0:9001"
#    enable_reflection_server: true
#    proto:
#        - "proto/service.proto"
